# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_playercam', [dirname(__file__)])
        except ImportError:
            import _playercam
            return _playercam
        if fp is not None:
            try:
                _mod = imp.load_module('_playercam', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _playercam = swig_import_helper()
    del swig_import_helper
else:
    import _playercam
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


MAXDEPTH = _playercam.MAXDEPTH
class Device(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Device, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Device, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _playercam.new_Device(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _playercam.delete_Device
    __del__ = lambda self : None;
    def initialize(self, *args): return _playercam.Device_initialize(self, *args)
    def getRGB(self): return _playercam.Device_getRGB(self)
    def setRGB(self, *args): return _playercam.Device_setRGB(self, *args)
    def getWidth(self): return _playercam.Device_getWidth(self)
    def getHeight(self): return _playercam.Device_getHeight(self)
    def getDepth(self): return _playercam.Device_getDepth(self)
    def getImage(self): return _playercam.Device_getImage(self)
    def getByte(self, *args): return _playercam.Device_getByte(self, *args)
Device_swigregister = _playercam.Device_swigregister
Device_swigregister(Device)

class PlayerCam(Device):
    __swig_setmethods__ = {}
    for _s in [Device]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, PlayerCam, name, value)
    __swig_getmethods__ = {}
    for _s in [Device]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, PlayerCam, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _playercam.new_PlayerCam(*args)
        try: self.this.append(this)
        except: self.this = this
    def updateMMap(self, *args): return _playercam.PlayerCam_updateMMap(self, *args)
    __swig_setmethods__["index"] = _playercam.PlayerCam_index_set
    __swig_getmethods__["index"] = _playercam.PlayerCam_index_get
    if _newclass:index = _swig_property(_playercam.PlayerCam_index_get, _playercam.PlayerCam_index_set)
    __swig_setmethods__["client"] = _playercam.PlayerCam_client_set
    __swig_getmethods__["client"] = _playercam.PlayerCam_client_get
    if _newclass:client = _swig_property(_playercam.PlayerCam_client_get, _playercam.PlayerCam_client_set)
    __swig_setmethods__["camDevice"] = _playercam.PlayerCam_camDevice_set
    __swig_getmethods__["camDevice"] = _playercam.PlayerCam_camDevice_get
    if _newclass:camDevice = _swig_property(_playercam.PlayerCam_camDevice_get, _playercam.PlayerCam_camDevice_set)
    __swig_destroy__ = _playercam.delete_PlayerCam
    __del__ = lambda self : None;
PlayerCam_swigregister = _playercam.PlayerCam_swigregister
PlayerCam_swigregister(PlayerCam)



