# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_aibo', [dirname(__file__)])
        except ImportError:
            import _aibo
            return _aibo
        if fp is not None:
            try:
                _mod = imp.load_module('_aibo', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _aibo = swig_import_helper()
    del swig_import_helper
else:
    import _aibo
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


MAXDEPTH = _aibo.MAXDEPTH
class Device(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Device, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Device, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _aibo.new_Device(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _aibo.delete_Device
    __del__ = lambda self : None;
    def initialize(self, *args): return _aibo.Device_initialize(self, *args)
    def getRGB(self): return _aibo.Device_getRGB(self)
    def setRGB(self, *args): return _aibo.Device_setRGB(self, *args)
    def getWidth(self): return _aibo.Device_getWidth(self)
    def getHeight(self): return _aibo.Device_getHeight(self)
    def getDepth(self): return _aibo.Device_getDepth(self)
    def getImage(self): return _aibo.Device_getImage(self)
    def getByte(self, *args): return _aibo.Device_getByte(self, *args)
Device_swigregister = _aibo.Device_swigregister
Device_swigregister(Device)

class AiboCam(Device):
    __swig_setmethods__ = {}
    for _s in [Device]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, AiboCam, name, value)
    __swig_getmethods__ = {}
    for _s in [Device]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, AiboCam, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _aibo.new_AiboCam(*args)
        try: self.this.append(this)
        except: self.this = this
    def updateMMap(self, *args): return _aibo.AiboCam_updateMMap(self, *args)
    __swig_setmethods__["sock"] = _aibo.AiboCam_sock_set
    __swig_getmethods__["sock"] = _aibo.AiboCam_sock_get
    if _newclass:sock = _swig_property(_aibo.AiboCam_sock_get, _aibo.AiboCam_sock_set)
    __swig_setmethods__["lock"] = _aibo.AiboCam_lock_set
    __swig_getmethods__["lock"] = _aibo.AiboCam_lock_get
    if _newclass:lock = _swig_property(_aibo.AiboCam_lock_get, _aibo.AiboCam_lock_set)
    __swig_setmethods__["tcp"] = _aibo.AiboCam_tcp_set
    __swig_getmethods__["tcp"] = _aibo.AiboCam_tcp_get
    if _newclass:tcp = _swig_property(_aibo.AiboCam_tcp_get, _aibo.AiboCam_tcp_set)
    __swig_destroy__ = _aibo.delete_AiboCam
    __del__ = lambda self : None;
AiboCam_swigregister = _aibo.AiboCam_swigregister
AiboCam_swigregister(AiboCam)

class Socket(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, Socket, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, Socket, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _aibo.new_Socket(*args)
        try: self.this.append(this)
        except: self.this = this
    def read(self, *args): return _aibo.Socket_read(self, *args)
    def readUntil(self, *args): return _aibo.Socket_readUntil(self, *args)
    def write(self, *args): return _aibo.Socket_write(self, *args)
    __swig_setmethods__["host"] = _aibo.Socket_host_set
    __swig_getmethods__["host"] = _aibo.Socket_host_get
    if _newclass:host = _swig_property(_aibo.Socket_host_get, _aibo.Socket_host_set)
    __swig_destroy__ = _aibo.delete_Socket
    __del__ = lambda self : None;
Socket_swigregister = _aibo.Socket_swigregister
Socket_swigregister(Socket)

class FakeSocket(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FakeSocket, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FakeSocket, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _aibo.new_FakeSocket(*args)
        try: self.this.append(this)
        except: self.this = this
    def read(self, *args): return _aibo.FakeSocket_read(self, *args)
    def readUntil(self, *args): return _aibo.FakeSocket_readUntil(self, *args)
    __swig_destroy__ = _aibo.delete_FakeSocket
    __del__ = lambda self : None;
FakeSocket_swigregister = _aibo.FakeSocket_swigregister
FakeSocket_swigregister(FakeSocket)



